version: '3.8'

services:
  stock-fetcher:
    build: .
    container_name: stock-fetcher
    restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      - ./stock_data:/app/stock_data
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s